SELECT TOP (1000) [FullName]
      ,[Total_Minutes]
      ,[Time]
      ,[Place]
      ,[City]
      ,[State]
      ,[Gender]
      ,[Age]
      ,[latitude]
      ,[longitude]
  FROM [Project].[dbo].[vw_ff_50]
